version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # no need to open ports if it used only inside internal docker network
  rails:
    # https://stackoverflow.com/questions/58933929/yarn-packages-out-of-date-when-running-rails-app-in-docker
    # problem is that we can not run yarn since mount volue will overwrite
    # node_modules, so we need to run yarn 
    environment:
      DATABASE_URL: postgresql://postgres:example@postgres:5432/move_index_production
    command: bash -c "bundle install && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    build: .
    volumes:
      - .:/myapp
    ports:
      - '80:3000'
    depends_on:
      - postgres
