name: Test

on:
  push:
      branches: [master]
  pull_request:
      branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      # those are used to connect from Rails
      PGHOST: localhost
      PGUSER: move_index
      PGPASSWORD: postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: move_index
          POSTGRES_DB: move_index_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports: [ "6379:6379"]
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.7.0
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -yqq install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install
      - name: Setup test database
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - name: Run tests
        run: |
          bundle exec rake
      - name: Run system tests
        run: |
          bundle exec rails test:system
